// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: chroma-calculator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstimateUnit int32

const (
	EstimateUnit_byte EstimateUnit = 0
	EstimateUnit_KB   EstimateUnit = 1
	EstimateUnit_MB   EstimateUnit = 2
	EstimateUnit_GB   EstimateUnit = 3
	EstimateUnit_TB   EstimateUnit = 4
)

// Enum value maps for EstimateUnit.
var (
	EstimateUnit_name = map[int32]string{
		0: "byte",
		1: "KB",
		2: "MB",
		3: "GB",
		4: "TB",
	}
	EstimateUnit_value = map[string]int32{
		"byte": 0,
		"KB":   1,
		"MB":   2,
		"GB":   3,
		"TB":   4,
	}
)

func (x EstimateUnit) Enum() *EstimateUnit {
	p := new(EstimateUnit)
	*p = x
	return p
}

func (x EstimateUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstimateUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_chroma_calculator_proto_enumTypes[0].Descriptor()
}

func (EstimateUnit) Type() protoreflect.EnumType {
	return &file_chroma_calculator_proto_enumTypes[0]
}

func (x EstimateUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstimateUnit.Descriptor instead.
func (EstimateUnit) EnumDescriptor() ([]byte, []int) {
	return file_chroma_calculator_proto_rawDescGZIP(), []int{0}
}

type CalculationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfVectors      int64    `protobuf:"varint,1,opt,name=number_of_vectors,json=numberOfVectors,proto3" json:"number_of_vectors,omitempty"`
	VectorDimensions     int64    `protobuf:"varint,2,opt,name=vector_dimensions,json=vectorDimensions,proto3" json:"vector_dimensions,omitempty"`
	SystemMemoryOverhead *float32 `protobuf:"fixed32,3,opt,name=system_memory_overhead,json=systemMemoryOverhead,proto3,oneof" json:"system_memory_overhead,omitempty"`
}

func (x *CalculationRequest) Reset() {
	*x = CalculationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chroma_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequest) ProtoMessage() {}

func (x *CalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chroma_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequest.ProtoReflect.Descriptor instead.
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return file_chroma_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculationRequest) GetNumberOfVectors() int64 {
	if x != nil {
		return x.NumberOfVectors
	}
	return 0
}

func (x *CalculationRequest) GetVectorDimensions() int64 {
	if x != nil {
		return x.VectorDimensions
	}
	return 0
}

func (x *CalculationRequest) GetSystemMemoryOverhead() float32 {
	if x != nil && x.SystemMemoryOverhead != nil {
		return *x.SystemMemoryOverhead
	}
	return 0
}

type CalculationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemorySizeEstimate float32      `protobuf:"fixed32,1,opt,name=memory_size_estimate,json=memorySizeEstimate,proto3" json:"memory_size_estimate,omitempty"`
	EstimateUnit       EstimateUnit `protobuf:"varint,2,opt,name=estimate_unit,json=estimateUnit,proto3,enum=calculator.EstimateUnit" json:"estimate_unit,omitempty"`
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chroma_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chroma_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_chroma_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationResponse) GetMemorySizeEstimate() float32 {
	if x != nil {
		return x.MemorySizeEstimate
	}
	return 0
}

func (x *CalculationResponse) GetEstimateUnit() EstimateUnit {
	if x != nil {
		return x.EstimateUnit
	}
	return EstimateUnit_byte
}

var File_chroma_calculator_proto protoreflect.FileDescriptor

var file_chroma_calculator_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x61, 0x2d, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xc3, 0x01, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x76, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x39, 0x0a, 0x16, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x14, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4f, 0x76, 0x65, 0x72, 0x68, 0x65, 0x61, 0x64, 0x88, 0x01, 0x01,
	0x42, 0x19, 0x0a, 0x17, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x68, 0x65, 0x61, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x13,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x5f, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x12, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x45, 0x73, 0x74,
	0x69, 0x6d, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61,
	0x74, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x0c, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x55, 0x6e, 0x69, 0x74, 0x2a, 0x38, 0x0a, 0x0c, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x55, 0x6e, 0x69, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x62, 0x79, 0x74, 0x65, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x4b, 0x42, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4d, 0x42, 0x10, 0x02, 0x12, 0x06,
	0x0a, 0x02, 0x47, 0x42, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x54, 0x42, 0x10, 0x04, 0x32, 0x61,
	0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x12, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_chroma_calculator_proto_rawDescOnce sync.Once
	file_chroma_calculator_proto_rawDescData = file_chroma_calculator_proto_rawDesc
)

func file_chroma_calculator_proto_rawDescGZIP() []byte {
	file_chroma_calculator_proto_rawDescOnce.Do(func() {
		file_chroma_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_chroma_calculator_proto_rawDescData)
	})
	return file_chroma_calculator_proto_rawDescData
}

var file_chroma_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chroma_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chroma_calculator_proto_goTypes = []interface{}{
	(EstimateUnit)(0),           // 0: calculator.EstimateUnit
	(*CalculationRequest)(nil),  // 1: calculator.CalculationRequest
	(*CalculationResponse)(nil), // 2: calculator.CalculationResponse
}
var file_chroma_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculationResponse.estimate_unit:type_name -> calculator.EstimateUnit
	1, // 1: calculator.CalculatorService.Calculate:input_type -> calculator.CalculationRequest
	2, // 2: calculator.CalculatorService.Calculate:output_type -> calculator.CalculationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chroma_calculator_proto_init() }
func file_chroma_calculator_proto_init() {
	if File_chroma_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chroma_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chroma_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_chroma_calculator_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chroma_calculator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chroma_calculator_proto_goTypes,
		DependencyIndexes: file_chroma_calculator_proto_depIdxs,
		EnumInfos:         file_chroma_calculator_proto_enumTypes,
		MessageInfos:      file_chroma_calculator_proto_msgTypes,
	}.Build()
	File_chroma_calculator_proto = out.File
	file_chroma_calculator_proto_rawDesc = nil
	file_chroma_calculator_proto_goTypes = nil
	file_chroma_calculator_proto_depIdxs = nil
}
